(memfn)
;; Omit (..) here, as macro-arity-check errors currently are fatal when linting (see object.go/PanicArityMinMax).
(defstruct)
(with-local-vars)
(definline)
(definterface)
(proxy-super)
(with-open)
(defrecord)
(..)
