// Auto-generated by gostd at 2019-09-17T13:14:28.216621211-04:00 by version 0.1, do not edit!!

package pprof

import (
	. "github.com/candid82/joker/core"
	_pprof "net/http/pprof"
)

// func __cmdline(__w ABEND987(genutils.go: imports not yet supported: http.ResponseWriter), __r *ABEND987(genutils.go: imports not yet supported: http.Request)) Object {
// 	_pprof.Cmdline(__w, __r)
// 	...ABEND675: TODO...
// }

func __handler(__name string) Object {
	_res := _pprof.Handler(__name)
	return MakeGoObject(_res)
}

// func __index(__w ABEND987(genutils.go: imports not yet supported: http.ResponseWriter), __r *ABEND987(genutils.go: imports not yet supported: http.Request)) Object {
// 	_pprof.Index(__w, __r)
// 	...ABEND675: TODO...
// }

// func __profile(__w ABEND987(genutils.go: imports not yet supported: http.ResponseWriter), __r *ABEND987(genutils.go: imports not yet supported: http.Request)) Object {
// 	_pprof.Profile(__w, __r)
// 	...ABEND675: TODO...
// }

// func __symbol(__w ABEND987(genutils.go: imports not yet supported: http.ResponseWriter), __r *ABEND987(genutils.go: imports not yet supported: http.Request)) Object {
// 	_pprof.Symbol(__w, __r)
// 	...ABEND675: TODO...
// }

// func __trace(__w ABEND987(genutils.go: imports not yet supported: http.ResponseWriter), __r *ABEND987(genutils.go: imports not yet supported: http.Request)) Object {
// 	_pprof.Trace(__w, __r)
// 	...ABEND675: TODO...
// }

func initNative() {
}
