// Auto-modified by gostd at 2020-01-31T23:21:08.266965-05:00 by version 0.1

package core

import (
	"archive/tar"
	"archive/zip"
	"bufio"
	"bytes"
	"compress/bzip2"
	"compress/flate"
	"compress/gzip"
	"compress/lzw"
	"compress/zlib"
	"container/heap"
	"container/list"
	"container/ring"
	"context"
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/des"
	"crypto/dsa"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rc4"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"database/sql"
	"database/sql/driver"
	"debug/dwarf"
	"debug/elf"
	"debug/gosym"
	"debug/macho"
	"debug/pe"
	"debug/plan9obj"
	"encoding"
	"encoding/ascii85"
	"encoding/asn1"
	"encoding/base32"
	"encoding/base64"
	"encoding/binary"
	"encoding/csv"
	"encoding/gob"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"encoding/xml"
	"expvar"
	"flag"
	"fmt"
	"go/ast"
	"go/build"
	"go/constant"
	"go/doc"
	"go/importer"
	"go/parser"
	"go/printer"
	"go/scanner"
	"go/token"
	"go/types"
	"hash"
	"hash/crc32"
	"hash/crc64"
	"html/template"
	"image"
	"image/color"
	"image/draw"
	"image/gif"
	"image/jpeg"
	"image/png"
	"index/suffixarray"
	"io"
	"log"
	"log/syslog"
	"math/big"
	"math/rand"
	"mime"
	"mime/multipart"
	"mime/quotedprintable"
	"net"
	"net/http"
	"net/http/cgi"
	"net/http/cookiejar"
	"net/http/httptest"
	"net/http/httptrace"
	"net/http/httputil"
	"net/mail"
	"net/rpc"
	"net/smtp"
	"net/textproto"
	"net/url"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"plugin"
	"reflect"
	"regexp"
	"regexp/syntax"
	"runtime"
	"runtime/debug"
	"runtime/pprof"
	"runtime/trace"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"syscall"
	"testing"
	"testing/quick"
	text_scanner "text/scanner"
	"text/tabwriter"
	text_template "text/template"
	"text/template/parse"
	"time"
	"unicode"
	"unsafe"
)

var GoTypesVec [1793]*GoTypeInfo

func SwitchGoType(g interface{}) int {
	switch g.(type) {
	case *tar.Format:
		return 0
	case *tar.Header:
		return 1
	case *tar.Reader:
		return 2
	case *tar.Writer:
		return 3
	case *zip.Compressor:
		return 4
	case *zip.Decompressor:
		return 5
	case *zip.File:
		return 6
	case *zip.FileHeader:
		return 7
	case *zip.ReadCloser:
		return 8
	case *zip.Reader:
		return 9
	case *zip.Writer:
		return 10
	case *bufio.ReadWriter:
		return 11
	case *bufio.Reader:
		return 12
	case *bufio.Scanner:
		return 13
	case *bufio.SplitFunc:
		return 14
	case *bufio.Writer:
		return 15
	case *bytes.Buffer:
		return 16
	case *bytes.Reader:
		return 17
	case *bzip2.StructuralError:
		return 18
	case *flate.CorruptInputError:
		return 19
	case *flate.InternalError:
		return 20
	case *flate.ReadError:
		return 21
	case *flate.WriteError:
		return 22
	case *flate.Writer:
		return 23
	case *gzip.Header:
		return 24
	case *gzip.Reader:
		return 25
	case *gzip.Writer:
		return 26
	case *lzw.Order:
		return 27
	case *zlib.Writer:
		return 28
	case *list.Element:
		return 29
	case *list.List:
		return 30
	case *ring.Ring:
		return 31
	case *context.CancelFunc:
		return 32
	case *aes.KeySizeError:
		return 33
	case *cipher.StreamReader:
		return 34
	case *cipher.StreamWriter:
		return 35
	case *des.KeySizeError:
		return 36
	case *dsa.ParameterSizes:
		return 37
	case *dsa.Parameters:
		return 38
	case *dsa.PrivateKey:
		return 39
	case *dsa.PublicKey:
		return 40
	case *ecdsa.PrivateKey:
		return 41
	case *ecdsa.PublicKey:
		return 42
	case *ed25519.PrivateKey:
		return 43
	case *ed25519.PublicKey:
		return 44
	case *elliptic.CurveParams:
		return 45
	case *rc4.Cipher:
		return 46
	case *rc4.KeySizeError:
		return 47
	case *rsa.CRTValue:
		return 48
	case *rsa.OAEPOptions:
		return 49
	case *rsa.PKCS1v15DecryptOptions:
		return 50
	case *rsa.PSSOptions:
		return 51
	case *rsa.PrecomputedValues:
		return 52
	case *rsa.PrivateKey:
		return 53
	case *rsa.PublicKey:
		return 54
	case *tls.Certificate:
		return 55
	case *tls.CertificateRequestInfo:
		return 56
	case *tls.ClientAuthType:
		return 57
	case *tls.ClientHelloInfo:
		return 58
	case *tls.ClientSessionState:
		return 59
	case *tls.Config:
		return 60
	case *tls.Conn:
		return 61
	case *tls.ConnectionState:
		return 62
	case *tls.CurveID:
		return 63
	case *tls.RecordHeaderError:
		return 64
	case *tls.RenegotiationSupport:
		return 65
	case *tls.SignatureScheme:
		return 66
	case *pkix.AlgorithmIdentifier:
		return 67
	case *pkix.AttributeTypeAndValue:
		return 68
	case *pkix.AttributeTypeAndValueSET:
		return 69
	case *pkix.CertificateList:
		return 70
	case *pkix.Extension:
		return 71
	case *pkix.Name:
		return 72
	case *pkix.RDNSequence:
		return 73
	case *pkix.RelativeDistinguishedNameSET:
		return 74
	case *pkix.RevokedCertificate:
		return 75
	case *pkix.TBSCertificateList:
		return 76
	case *x509.CertPool:
		return 77
	case *x509.Certificate:
		return 78
	case *x509.CertificateInvalidError:
		return 79
	case *x509.CertificateRequest:
		return 80
	case *x509.ConstraintViolationError:
		return 81
	case *x509.ExtKeyUsage:
		return 82
	case *x509.HostnameError:
		return 83
	case *x509.InsecureAlgorithmError:
		return 84
	case *x509.InvalidReason:
		return 85
	case *x509.KeyUsage:
		return 86
	case *x509.PEMCipher:
		return 87
	case *x509.PublicKeyAlgorithm:
		return 88
	case *x509.SignatureAlgorithm:
		return 89
	case *x509.SystemRootsError:
		return 90
	case *x509.UnhandledCriticalExtension:
		return 91
	case *x509.UnknownAuthorityError:
		return 92
	case *x509.VerifyOptions:
		return 93
	case *crypto.Hash:
		return 94
	case *driver.IsolationLevel:
		return 95
	case *driver.NamedValue:
		return 96
	case *driver.NotNull:
		return 97
	case *driver.Null:
		return 98
	case *driver.RowsAffected:
		return 99
	case *driver.TxOptions:
		return 100
	case *sql.ColumnType:
		return 101
	case *sql.Conn:
		return 102
	case *sql.DB:
		return 103
	case *sql.DBStats:
		return 104
	case *sql.IsolationLevel:
		return 105
	case *sql.NamedArg:
		return 106
	case *sql.NullBool:
		return 107
	case *sql.NullFloat64:
		return 108
	case *sql.NullInt32:
		return 109
	case *sql.NullInt64:
		return 110
	case *sql.NullString:
		return 111
	case *sql.NullTime:
		return 112
	case *sql.Out:
		return 113
	case *sql.RawBytes:
		return 114
	case *sql.Row:
		return 115
	case *sql.Rows:
		return 116
	case *sql.Stmt:
		return 117
	case *sql.Tx:
		return 118
	case *sql.TxOptions:
		return 119
	case *dwarf.AddrType:
		return 120
	case *dwarf.ArrayType:
		return 121
	case *dwarf.Attr:
		return 122
	case *dwarf.BasicType:
		return 123
	case *dwarf.BoolType:
		return 124
	case *dwarf.CharType:
		return 125
	case *dwarf.Class:
		return 126
	case *dwarf.CommonType:
		return 127
	case *dwarf.ComplexType:
		return 128
	case *dwarf.Data:
		return 129
	case *dwarf.DecodeError:
		return 130
	case *dwarf.DotDotDotType:
		return 131
	case *dwarf.Entry:
		return 132
	case *dwarf.EnumType:
		return 133
	case *dwarf.EnumValue:
		return 134
	case *dwarf.Field:
		return 135
	case *dwarf.FloatType:
		return 136
	case *dwarf.FuncType:
		return 137
	case *dwarf.IntType:
		return 138
	case *dwarf.LineEntry:
		return 139
	case *dwarf.LineFile:
		return 140
	case *dwarf.LineReader:
		return 141
	case *dwarf.LineReaderPos:
		return 142
	case *dwarf.Offset:
		return 143
	case *dwarf.PtrType:
		return 144
	case *dwarf.QualType:
		return 145
	case *dwarf.Reader:
		return 146
	case *dwarf.StructField:
		return 147
	case *dwarf.StructType:
		return 148
	case *dwarf.Tag:
		return 149
	case *dwarf.TypedefType:
		return 150
	case *dwarf.UcharType:
		return 151
	case *dwarf.UintType:
		return 152
	case *dwarf.UnspecifiedType:
		return 153
	case *dwarf.UnsupportedType:
		return 154
	case *dwarf.VoidType:
		return 155
	case *elf.Chdr32:
		return 156
	case *elf.Chdr64:
		return 157
	case *elf.Class:
		return 158
	case *elf.CompressionType:
		return 159
	case *elf.Data:
		return 160
	case *elf.Dyn32:
		return 161
	case *elf.Dyn64:
		return 162
	case *elf.DynFlag:
		return 163
	case *elf.DynTag:
		return 164
	case *elf.File:
		return 165
	case *elf.FileHeader:
		return 166
	case *elf.FormatError:
		return 167
	case *elf.Header32:
		return 168
	case *elf.Header64:
		return 169
	case *elf.ImportedSymbol:
		return 170
	case *elf.Machine:
		return 171
	case *elf.NType:
		return 172
	case *elf.OSABI:
		return 173
	case *elf.Prog:
		return 174
	case *elf.Prog32:
		return 175
	case *elf.Prog64:
		return 176
	case *elf.ProgFlag:
		return 177
	case *elf.ProgHeader:
		return 178
	case *elf.ProgType:
		return 179
	case *elf.R_386:
		return 180
	case *elf.R_390:
		return 181
	case *elf.R_AARCH64:
		return 182
	case *elf.R_ALPHA:
		return 183
	case *elf.R_ARM:
		return 184
	case *elf.R_MIPS:
		return 185
	case *elf.R_PPC:
		return 186
	case *elf.R_PPC64:
		return 187
	case *elf.R_RISCV:
		return 188
	case *elf.R_SPARC:
		return 189
	case *elf.R_X86_64:
		return 190
	case *elf.Rel32:
		return 191
	case *elf.Rel64:
		return 192
	case *elf.Rela32:
		return 193
	case *elf.Rela64:
		return 194
	case *elf.Section:
		return 195
	case *elf.Section32:
		return 196
	case *elf.Section64:
		return 197
	case *elf.SectionFlag:
		return 198
	case *elf.SectionHeader:
		return 199
	case *elf.SectionIndex:
		return 200
	case *elf.SectionType:
		return 201
	case *elf.Sym32:
		return 202
	case *elf.Sym64:
		return 203
	case *elf.SymBind:
		return 204
	case *elf.SymType:
		return 205
	case *elf.SymVis:
		return 206
	case *elf.Symbol:
		return 207
	case *elf.Type:
		return 208
	case *elf.Version:
		return 209
	case *gosym.DecodingError:
		return 210
	case *gosym.Func:
		return 211
	case *gosym.LineTable:
		return 212
	case *gosym.Obj:
		return 213
	case *gosym.Sym:
		return 214
	case *gosym.Table:
		return 215
	case *gosym.UnknownFileError:
		return 216
	case *gosym.UnknownLineError:
		return 217
	case *macho.Cpu:
		return 218
	case *macho.Dylib:
		return 219
	case *macho.DylibCmd:
		return 220
	case *macho.Dysymtab:
		return 221
	case *macho.DysymtabCmd:
		return 222
	case *macho.FatArch:
		return 223
	case *macho.FatArchHeader:
		return 224
	case *macho.FatFile:
		return 225
	case *macho.File:
		return 226
	case *macho.FileHeader:
		return 227
	case *macho.FormatError:
		return 228
	case *macho.LoadBytes:
		return 229
	case *macho.LoadCmd:
		return 230
	case *macho.Nlist32:
		return 231
	case *macho.Nlist64:
		return 232
	case *macho.Regs386:
		return 233
	case *macho.RegsAMD64:
		return 234
	case *macho.Reloc:
		return 235
	case *macho.RelocTypeARM:
		return 236
	case *macho.RelocTypeARM64:
		return 237
	case *macho.RelocTypeGeneric:
		return 238
	case *macho.RelocTypeX86_64:
		return 239
	case *macho.Rpath:
		return 240
	case *macho.RpathCmd:
		return 241
	case *macho.Section:
		return 242
	case *macho.Section32:
		return 243
	case *macho.Section64:
		return 244
	case *macho.SectionHeader:
		return 245
	case *macho.Segment:
		return 246
	case *macho.Segment32:
		return 247
	case *macho.Segment64:
		return 248
	case *macho.SegmentHeader:
		return 249
	case *macho.Symbol:
		return 250
	case *macho.Symtab:
		return 251
	case *macho.SymtabCmd:
		return 252
	case *macho.Thread:
		return 253
	case *macho.Type:
		return 254
	case *pe.COFFSymbol:
		return 255
	case *pe.DataDirectory:
		return 256
	case *pe.File:
		return 257
	case *pe.FileHeader:
		return 258
	case *pe.FormatError:
		return 259
	case *pe.ImportDirectory:
		return 260
	case *pe.OptionalHeader32:
		return 261
	case *pe.OptionalHeader64:
		return 262
	case *pe.Reloc:
		return 263
	case *pe.Section:
		return 264
	case *pe.SectionHeader:
		return 265
	case *pe.SectionHeader32:
		return 266
	case *pe.StringTable:
		return 267
	case *pe.Symbol:
		return 268
	case *plan9obj.File:
		return 269
	case *plan9obj.FileHeader:
		return 270
	case *plan9obj.Section:
		return 271
	case *plan9obj.SectionHeader:
		return 272
	case *plan9obj.Sym:
		return 273
	case *ascii85.CorruptInputError:
		return 274
	case *asn1.BitString:
		return 275
	case *asn1.Enumerated:
		return 276
	case *asn1.Flag:
		return 277
	case *asn1.ObjectIdentifier:
		return 278
	case *asn1.RawContent:
		return 279
	case *asn1.RawValue:
		return 280
	case *asn1.StructuralError:
		return 281
	case *asn1.SyntaxError:
		return 282
	case *base32.CorruptInputError:
		return 283
	case *base32.Encoding:
		return 284
	case *base64.CorruptInputError:
		return 285
	case *base64.Encoding:
		return 286
	case *csv.ParseError:
		return 287
	case *csv.Reader:
		return 288
	case *csv.Writer:
		return 289
	case *gob.CommonType:
		return 290
	case *gob.Decoder:
		return 291
	case *gob.Encoder:
		return 292
	case *hex.InvalidByteError:
		return 293
	case *json.Decoder:
		return 294
	case *json.Delim:
		return 295
	case *json.Encoder:
		return 296
	case *json.InvalidUTF8Error:
		return 297
	case *json.InvalidUnmarshalError:
		return 298
	case *json.MarshalerError:
		return 299
	case *json.Number:
		return 300
	case *json.RawMessage:
		return 301
	case *json.SyntaxError:
		return 302
	case *json.UnmarshalFieldError:
		return 303
	case *json.UnmarshalTypeError:
		return 304
	case *json.UnsupportedTypeError:
		return 305
	case *json.UnsupportedValueError:
		return 306
	case *pem.Block:
		return 307
	case *xml.Attr:
		return 308
	case *xml.CharData:
		return 309
	case *xml.Comment:
		return 310
	case *xml.Decoder:
		return 311
	case *xml.Directive:
		return 312
	case *xml.Encoder:
		return 313
	case *xml.EndElement:
		return 314
	case *xml.Name:
		return 315
	case *xml.ProcInst:
		return 316
	case *xml.StartElement:
		return 317
	case *xml.SyntaxError:
		return 318
	case *xml.TagPathError:
		return 319
	case *xml.UnmarshalError:
		return 320
	case *xml.UnsupportedTypeError:
		return 321
	case *expvar.Float:
		return 322
	case *expvar.Func:
		return 323
	case *expvar.Int:
		return 324
	case *expvar.KeyValue:
		return 325
	case *expvar.Map:
		return 326
	case *expvar.String:
		return 327
	case *flag.ErrorHandling:
		return 328
	case *flag.Flag:
		return 329
	case *flag.FlagSet:
		return 330
	case *ast.ArrayType:
		return 331
	case *ast.AssignStmt:
		return 332
	case *ast.BadDecl:
		return 333
	case *ast.BadExpr:
		return 334
	case *ast.BadStmt:
		return 335
	case *ast.BasicLit:
		return 336
	case *ast.BinaryExpr:
		return 337
	case *ast.BlockStmt:
		return 338
	case *ast.BranchStmt:
		return 339
	case *ast.CallExpr:
		return 340
	case *ast.CaseClause:
		return 341
	case *ast.ChanDir:
		return 342
	case *ast.ChanType:
		return 343
	case *ast.CommClause:
		return 344
	case *ast.Comment:
		return 345
	case *ast.CommentGroup:
		return 346
	case *ast.CommentMap:
		return 347
	case *ast.CompositeLit:
		return 348
	case *ast.DeclStmt:
		return 349
	case *ast.DeferStmt:
		return 350
	case *ast.Ellipsis:
		return 351
	case *ast.EmptyStmt:
		return 352
	case *ast.ExprStmt:
		return 353
	case *ast.Field:
		return 354
	case *ast.FieldFilter:
		return 355
	case *ast.FieldList:
		return 356
	case *ast.File:
		return 357
	case *ast.Filter:
		return 358
	case *ast.ForStmt:
		return 359
	case *ast.FuncDecl:
		return 360
	case *ast.FuncLit:
		return 361
	case *ast.FuncType:
		return 362
	case *ast.GenDecl:
		return 363
	case *ast.GoStmt:
		return 364
	case *ast.Ident:
		return 365
	case *ast.IfStmt:
		return 366
	case *ast.ImportSpec:
		return 367
	case *ast.Importer:
		return 368
	case *ast.IncDecStmt:
		return 369
	case *ast.IndexExpr:
		return 370
	case *ast.InterfaceType:
		return 371
	case *ast.KeyValueExpr:
		return 372
	case *ast.LabeledStmt:
		return 373
	case *ast.MapType:
		return 374
	case *ast.MergeMode:
		return 375
	case *ast.ObjKind:
		return 376
	case *ast.Object:
		return 377
	case *ast.Package:
		return 378
	case *ast.ParenExpr:
		return 379
	case *ast.RangeStmt:
		return 380
	case *ast.ReturnStmt:
		return 381
	case *ast.Scope:
		return 382
	case *ast.SelectStmt:
		return 383
	case *ast.SelectorExpr:
		return 384
	case *ast.SendStmt:
		return 385
	case *ast.SliceExpr:
		return 386
	case *ast.StarExpr:
		return 387
	case *ast.StructType:
		return 388
	case *ast.SwitchStmt:
		return 389
	case *ast.TypeAssertExpr:
		return 390
	case *ast.TypeSpec:
		return 391
	case *ast.TypeSwitchStmt:
		return 392
	case *ast.UnaryExpr:
		return 393
	case *ast.ValueSpec:
		return 394
	case *build.Context:
		return 395
	case *build.ImportMode:
		return 396
	case *build.MultiplePackageError:
		return 397
	case *build.NoGoError:
		return 398
	case *build.Package:
		return 399
	case *constant.Kind:
		return 400
	case *doc.Example:
		return 401
	case *doc.Filter:
		return 402
	case *doc.Func:
		return 403
	case *doc.Mode:
		return 404
	case *doc.Note:
		return 405
	case *doc.Package:
		return 406
	case *doc.Type:
		return 407
	case *doc.Value:
		return 408
	case *importer.Lookup:
		return 409
	case *parser.Mode:
		return 410
	case *printer.CommentedNode:
		return 411
	case *printer.Config:
		return 412
	case *printer.Mode:
		return 413
	case *scanner.Error:
		return 414
	case *scanner.ErrorHandler:
		return 415
	case *scanner.ErrorList:
		return 416
	case *scanner.Mode:
		return 417
	case *scanner.Scanner:
		return 418
	case *token.File:
		return 419
	case *token.FileSet:
		return 420
	case *token.Pos:
		return 421
	case *token.Position:
		return 422
	case *token.Token:
		return 423
	case *types.Array:
		return 424
	case *types.Basic:
		return 425
	case *types.BasicInfo:
		return 426
	case *types.BasicKind:
		return 427
	case *types.Builtin:
		return 428
	case *types.Chan:
		return 429
	case *types.ChanDir:
		return 430
	case *types.Checker:
		return 431
	case *types.Config:
		return 432
	case *types.Const:
		return 433
	case *types.Error:
		return 434
	case *types.Func:
		return 435
	case *types.ImportMode:
		return 436
	case *types.Info:
		return 437
	case *types.Initializer:
		return 438
	case *types.Interface:
		return 439
	case *types.Label:
		return 440
	case *types.Map:
		return 441
	case *types.MethodSet:
		return 442
	case *types.Named:
		return 443
	case *types.Nil:
		return 444
	case *types.Package:
		return 445
	case *types.PkgName:
		return 446
	case *types.Pointer:
		return 447
	case *types.Qualifier:
		return 448
	case *types.Scope:
		return 449
	case *types.Selection:
		return 450
	case *types.SelectionKind:
		return 451
	case *types.Signature:
		return 452
	case *types.Slice:
		return 453
	case *types.StdSizes:
		return 454
	case *types.Struct:
		return 455
	case *types.Tuple:
		return 456
	case *types.TypeAndValue:
		return 457
	case *types.TypeName:
		return 458
	case *types.Var:
		return 459
	case *crc32.Table:
		return 460
	case *crc64.Table:
		return 461
	case *template.CSS:
		return 462
	case *template.Error:
		return 463
	case *template.ErrorCode:
		return 464
	case *template.FuncMap:
		return 465
	case *template.HTML:
		return 466
	case *template.HTMLAttr:
		return 467
	case *template.JS:
		return 468
	case *template.JSStr:
		return 469
	case *template.Srcset:
		return 470
	case *template.Template:
		return 471
	case *template.URL:
		return 472
	case *color.Alpha:
		return 473
	case *color.Alpha16:
		return 474
	case *color.CMYK:
		return 475
	case *color.Gray:
		return 476
	case *color.Gray16:
		return 477
	case *color.NRGBA:
		return 478
	case *color.NRGBA64:
		return 479
	case *color.NYCbCrA:
		return 480
	case *color.Palette:
		return 481
	case *color.RGBA:
		return 482
	case *color.RGBA64:
		return 483
	case *color.YCbCr:
		return 484
	case *draw.Op:
		return 485
	case *gif.GIF:
		return 486
	case *gif.Options:
		return 487
	case *jpeg.FormatError:
		return 488
	case *jpeg.Options:
		return 489
	case *jpeg.UnsupportedError:
		return 490
	case *png.CompressionLevel:
		return 491
	case *png.Encoder:
		return 492
	case *png.EncoderBuffer:
		return 493
	case *png.FormatError:
		return 494
	case *png.UnsupportedError:
		return 495
	case *image.Alpha:
		return 496
	case *image.Alpha16:
		return 497
	case *image.CMYK:
		return 498
	case *image.Config:
		return 499
	case *image.Gray:
		return 500
	case *image.Gray16:
		return 501
	case *image.NRGBA:
		return 502
	case *image.NRGBA64:
		return 503
	case *image.NYCbCrA:
		return 504
	case *image.Paletted:
		return 505
	case *image.Point:
		return 506
	case *image.RGBA:
		return 507
	case *image.RGBA64:
		return 508
	case *image.Rectangle:
		return 509
	case *image.Uniform:
		return 510
	case *image.YCbCr:
		return 511
	case *image.YCbCrSubsampleRatio:
		return 512
	case *suffixarray.Index:
		return 513
	case *io.LimitedReader:
		return 514
	case *io.PipeReader:
		return 515
	case *io.PipeWriter:
		return 516
	case *io.SectionReader:
		return 517
	case *syslog.Priority:
		return 518
	case *syslog.Writer:
		return 519
	case *log.Logger:
		return 520
	case *big.Accuracy:
		return 521
	case *big.ErrNaN:
		return 522
	case *big.Float:
		return 523
	case *big.Int:
		return 524
	case *big.Rat:
		return 525
	case *big.RoundingMode:
		return 526
	case *big.Word:
		return 527
	case *rand.Rand:
		return 528
	case *rand.Zipf:
		return 529
	case *multipart.FileHeader:
		return 530
	case *multipart.Form:
		return 531
	case *multipart.Part:
		return 532
	case *multipart.Reader:
		return 533
	case *multipart.Writer:
		return 534
	case *quotedprintable.Reader:
		return 535
	case *quotedprintable.Writer:
		return 536
	case *mime.WordDecoder:
		return 537
	case *mime.WordEncoder:
		return 538
	case *cgi.Handler:
		return 539
	case *cookiejar.Jar:
		return 540
	case *cookiejar.Options:
		return 541
	case *httptest.ResponseRecorder:
		return 542
	case *httptest.Server:
		return 543
	case *httptrace.ClientTrace:
		return 544
	case *httptrace.DNSDoneInfo:
		return 545
	case *httptrace.DNSStartInfo:
		return 546
	case *httptrace.GotConnInfo:
		return 547
	case *httptrace.WroteRequestInfo:
		return 548
	case *httputil.ClientConn:
		return 549
	case *httputil.ReverseProxy:
		return 550
	case *httputil.ServerConn:
		return 551
	case *http.Client:
		return 552
	case *http.ConnState:
		return 553
	case *http.Cookie:
		return 554
	case *http.Dir:
		return 555
	case *http.HandlerFunc:
		return 556
	case *http.Header:
		return 557
	case *http.ProtocolError:
		return 558
	case *http.PushOptions:
		return 559
	case *http.Request:
		return 560
	case *http.Response:
		return 561
	case *http.SameSite:
		return 562
	case *http.ServeMux:
		return 563
	case *http.Server:
		return 564
	case *http.Transport:
		return 565
	case *mail.Address:
		return 566
	case *mail.AddressParser:
		return 567
	case *mail.Header:
		return 568
	case *mail.Message:
		return 569
	case *rpc.Call:
		return 570
	case *rpc.Client:
		return 571
	case *rpc.Request:
		return 572
	case *rpc.Response:
		return 573
	case *rpc.Server:
		return 574
	case *rpc.ServerError:
		return 575
	case *smtp.Client:
		return 576
	case *smtp.ServerInfo:
		return 577
	case *textproto.Conn:
		return 578
	case *textproto.Error:
		return 579
	case *textproto.MIMEHeader:
		return 580
	case *textproto.Pipeline:
		return 581
	case *textproto.ProtocolError:
		return 582
	case *textproto.Reader:
		return 583
	case *textproto.Writer:
		return 584
	case *url.Error:
		return 585
	case *url.EscapeError:
		return 586
	case *url.InvalidHostError:
		return 587
	case *url.URL:
		return 588
	case *url.Userinfo:
		return 589
	case *url.Values:
		return 590
	case *net.AddrError:
		return 591
	case *net.Buffers:
		return 592
	case *net.DNSConfigError:
		return 593
	case *net.DNSError:
		return 594
	case *net.Dialer:
		return 595
	case *net.Flags:
		return 596
	case *net.HardwareAddr:
		return 597
	case *net.IP:
		return 598
	case *net.IPAddr:
		return 599
	case *net.IPConn:
		return 600
	case *net.IPMask:
		return 601
	case *net.IPNet:
		return 602
	case *net.Interface:
		return 603
	case *net.InvalidAddrError:
		return 604
	case *net.ListenConfig:
		return 605
	case *net.MX:
		return 606
	case *net.NS:
		return 607
	case *net.OpError:
		return 608
	case *net.ParseError:
		return 609
	case *net.Resolver:
		return 610
	case *net.SRV:
		return 611
	case *net.TCPAddr:
		return 612
	case *net.TCPConn:
		return 613
	case *net.TCPListener:
		return 614
	case *net.UDPAddr:
		return 615
	case *net.UDPConn:
		return 616
	case *net.UnixAddr:
		return 617
	case *net.UnixConn:
		return 618
	case *net.UnixListener:
		return 619
	case *net.UnknownNetworkError:
		return 620
	case *exec.Cmd:
		return 621
	case *exec.Error:
		return 622
	case *exec.ExitError:
		return 623
	case *user.Group:
		return 624
	case *user.UnknownGroupError:
		return 625
	case *user.UnknownGroupIdError:
		return 626
	case *user.UnknownUserError:
		return 627
	case *user.UnknownUserIdError:
		return 628
	case *user.User:
		return 629
	case *os.File:
		return 630
	case *os.FileMode:
		return 631
	case *os.LinkError:
		return 632
	case *os.PathError:
		return 633
	case *os.ProcAttr:
		return 634
	case *os.Process:
		return 635
	case *os.ProcessState:
		return 636
	case *os.SyscallError:
		return 637
	case *filepath.WalkFunc:
		return 638
	case *plugin.Plugin:
		return 639
	case *reflect.ChanDir:
		return 640
	case *reflect.Kind:
		return 641
	case *reflect.MapIter:
		return 642
	case *reflect.Method:
		return 643
	case *reflect.SelectCase:
		return 644
	case *reflect.SelectDir:
		return 645
	case *reflect.SliceHeader:
		return 646
	case *reflect.StringHeader:
		return 647
	case *reflect.StructField:
		return 648
	case *reflect.StructTag:
		return 649
	case *reflect.Value:
		return 650
	case *reflect.ValueError:
		return 651
	case *syntax.EmptyOp:
		return 652
	case *syntax.Error:
		return 653
	case *syntax.ErrorCode:
		return 654
	case *syntax.Flags:
		return 655
	case *syntax.Inst:
		return 656
	case *syntax.InstOp:
		return 657
	case *syntax.Op:
		return 658
	case *syntax.Prog:
		return 659
	case *syntax.Regexp:
		return 660
	case *regexp.Regexp:
		return 661
	case *debug.BuildInfo:
		return 662
	case *debug.GCStats:
		return 663
	case *debug.Module:
		return 664
	case *pprof.LabelSet:
		return 665
	case *pprof.Profile:
		return 666
	case *trace.Region:
		return 667
	case *trace.Task:
		return 668
	case *runtime.BlockProfileRecord:
		return 669
	case *runtime.Frame:
		return 670
	case *runtime.Frames:
		return 671
	case *runtime.Func:
		return 672
	case *runtime.MemProfileRecord:
		return 673
	case *runtime.MemStats:
		return 674
	case *runtime.StackRecord:
		return 675
	case *runtime.TypeAssertionError:
		return 676
	case *sort.Float64Slice:
		return 677
	case *sort.IntSlice:
		return 678
	case *sort.StringSlice:
		return 679
	case *strconv.NumError:
		return 680
	case *strings.Builder:
		return 681
	case *strings.Reader:
		return 682
	case *strings.Replacer:
		return 683
	case *atomic.Value:
		return 684
	case *sync.Cond:
		return 685
	case *sync.Map:
		return 686
	case *sync.Mutex:
		return 687
	case *sync.Once:
		return 688
	case *sync.Pool:
		return 689
	case *sync.RWMutex:
		return 690
	case *sync.WaitGroup:
		return 691
	case *syscall.BpfHdr:
		return 692
	case *syscall.BpfInsn:
		return 693
	case *syscall.BpfProgram:
		return 694
	case *syscall.BpfStat:
		return 695
	case *syscall.BpfVersion:
		return 696
	case *syscall.Cmsghdr:
		return 697
	case *syscall.Credential:
		return 698
	case *syscall.Dirent:
		return 699
	case *syscall.Errno:
		return 700
	case *syscall.Fbootstraptransfer_t:
		return 701
	case *syscall.FdSet:
		return 702
	case *syscall.Flock_t:
		return 703
	case *syscall.Fsid:
		return 704
	case *syscall.Fstore_t:
		return 705
	case *syscall.ICMPv6Filter:
		return 706
	case *syscall.IPMreq:
		return 707
	case *syscall.IPv6MTUInfo:
		return 708
	case *syscall.IPv6Mreq:
		return 709
	case *syscall.IfData:
		return 710
	case *syscall.IfMsghdr:
		return 711
	case *syscall.IfaMsghdr:
		return 712
	case *syscall.IfmaMsghdr:
		return 713
	case *syscall.IfmaMsghdr2:
		return 714
	case *syscall.Inet4Pktinfo:
		return 715
	case *syscall.Inet6Pktinfo:
		return 716
	case *syscall.InterfaceAddrMessage:
		return 717
	case *syscall.InterfaceMessage:
		return 718
	case *syscall.InterfaceMulticastAddrMessage:
		return 719
	case *syscall.Iovec:
		return 720
	case *syscall.Kevent_t:
		return 721
	case *syscall.Linger:
		return 722
	case *syscall.Log2phys_t:
		return 723
	case *syscall.Msghdr:
		return 724
	case *syscall.ProcAttr:
		return 725
	case *syscall.Radvisory_t:
		return 726
	case *syscall.RawSockaddr:
		return 727
	case *syscall.RawSockaddrAny:
		return 728
	case *syscall.RawSockaddrDatalink:
		return 729
	case *syscall.RawSockaddrInet4:
		return 730
	case *syscall.RawSockaddrInet6:
		return 731
	case *syscall.RawSockaddrUnix:
		return 732
	case *syscall.Rlimit:
		return 733
	case *syscall.RouteMessage:
		return 734
	case *syscall.RtMetrics:
		return 735
	case *syscall.RtMsghdr:
		return 736
	case *syscall.Rusage:
		return 737
	case *syscall.Signal:
		return 738
	case *syscall.SockaddrDatalink:
		return 739
	case *syscall.SockaddrInet4:
		return 740
	case *syscall.SockaddrInet6:
		return 741
	case *syscall.SockaddrUnix:
		return 742
	case *syscall.SocketControlMessage:
		return 743
	case *syscall.Stat_t:
		return 744
	case *syscall.Statfs_t:
		return 745
	case *syscall.SysProcAttr:
		return 746
	case *syscall.Termios:
		return 747
	case *syscall.Timespec:
		return 748
	case *syscall.Timeval:
		return 749
	case *syscall.Timeval32:
		return 750
	case *syscall.WaitStatus:
		return 751
	case *quick.CheckEqualError:
		return 752
	case *quick.CheckError:
		return 753
	case *quick.Config:
		return 754
	case *quick.SetupError:
		return 755
	case *testing.B:
		return 756
	case *testing.BenchmarkResult:
		return 757
	case *testing.Cover:
		return 758
	case *testing.CoverBlock:
		return 759
	case *testing.InternalBenchmark:
		return 760
	case *testing.InternalExample:
		return 761
	case *testing.InternalTest:
		return 762
	case *testing.M:
		return 763
	case *testing.PB:
		return 764
	case *testing.T:
		return 765
	case *text_scanner.Position:
		return 766
	case *text_scanner.Scanner:
		return 767
	case *tabwriter.Writer:
		return 768
	case *parse.ActionNode:
		return 769
	case *parse.BoolNode:
		return 770
	case *parse.BranchNode:
		return 771
	case *parse.ChainNode:
		return 772
	case *parse.CommandNode:
		return 773
	case *parse.DotNode:
		return 774
	case *parse.FieldNode:
		return 775
	case *parse.IdentifierNode:
		return 776
	case *parse.IfNode:
		return 777
	case *parse.ListNode:
		return 778
	case *parse.NilNode:
		return 779
	case *parse.NodeType:
		return 780
	case *parse.NumberNode:
		return 781
	case *parse.PipeNode:
		return 782
	case *parse.Pos:
		return 783
	case *parse.RangeNode:
		return 784
	case *parse.StringNode:
		return 785
	case *parse.TemplateNode:
		return 786
	case *parse.TextNode:
		return 787
	case *parse.Tree:
		return 788
	case *parse.VariableNode:
		return 789
	case *parse.WithNode:
		return 790
	case *text_template.ExecError:
		return 791
	case *text_template.FuncMap:
		return 792
	case *text_template.Template:
		return 793
	case *time.Duration:
		return 794
	case *time.Location:
		return 795
	case *time.Month:
		return 796
	case *time.ParseError:
		return 797
	case *time.Ticker:
		return 798
	case *time.Time:
		return 799
	case *time.Timer:
		return 800
	case *time.Weekday:
		return 801
	case *unicode.CaseRange:
		return 802
	case *unicode.Range16:
		return 803
	case *unicode.Range32:
		return 804
	case *unicode.RangeTable:
		return 805
	case *unicode.SpecialCase:
		return 806
	case *unsafe.Pointer:
		return 807
	case tar.Format:
		return 808
	case tar.Header:
		return 809
	case tar.Reader:
		return 810
	case tar.Writer:
		return 811
	case zip.Compressor:
		return 812
	case zip.Decompressor:
		return 813
	case zip.File:
		return 814
	case zip.FileHeader:
		return 815
	case zip.ReadCloser:
		return 816
	case zip.Reader:
		return 817
	case zip.Writer:
		return 818
	case bufio.ReadWriter:
		return 819
	case bufio.Reader:
		return 820
	case bufio.Scanner:
		return 821
	case bufio.SplitFunc:
		return 822
	case bufio.Writer:
		return 823
	case bytes.Buffer:
		return 824
	case bytes.Reader:
		return 825
	case bzip2.StructuralError:
		return 826
	case flate.CorruptInputError:
		return 827
	case flate.InternalError:
		return 828
	case flate.ReadError:
		return 829
	case flate.WriteError:
		return 830
	case flate.Writer:
		return 831
	case gzip.Header:
		return 832
	case gzip.Reader:
		return 833
	case gzip.Writer:
		return 834
	case lzw.Order:
		return 835
	case zlib.Writer:
		return 836
	case list.Element:
		return 837
	case list.List:
		return 838
	case ring.Ring:
		return 839
	case context.CancelFunc:
		return 840
	case aes.KeySizeError:
		return 841
	case cipher.StreamReader:
		return 842
	case cipher.StreamWriter:
		return 843
	case des.KeySizeError:
		return 844
	case dsa.ParameterSizes:
		return 845
	case dsa.Parameters:
		return 846
	case dsa.PrivateKey:
		return 847
	case dsa.PublicKey:
		return 848
	case ecdsa.PrivateKey:
		return 849
	case ecdsa.PublicKey:
		return 850
	case ed25519.PrivateKey:
		return 851
	case ed25519.PublicKey:
		return 852
	case elliptic.CurveParams:
		return 853
	case rc4.Cipher:
		return 854
	case rc4.KeySizeError:
		return 855
	case rsa.CRTValue:
		return 856
	case rsa.OAEPOptions:
		return 857
	case rsa.PKCS1v15DecryptOptions:
		return 858
	case rsa.PSSOptions:
		return 859
	case rsa.PrecomputedValues:
		return 860
	case rsa.PrivateKey:
		return 861
	case rsa.PublicKey:
		return 862
	case tls.Certificate:
		return 863
	case tls.CertificateRequestInfo:
		return 864
	case tls.ClientAuthType:
		return 865
	case tls.ClientHelloInfo:
		return 866
	case tls.ClientSessionState:
		return 867
	case tls.Config:
		return 868
	case tls.Conn:
		return 869
	case tls.ConnectionState:
		return 870
	case tls.CurveID:
		return 871
	case tls.RecordHeaderError:
		return 872
	case tls.RenegotiationSupport:
		return 873
	case tls.SignatureScheme:
		return 874
	case pkix.AlgorithmIdentifier:
		return 875
	case pkix.AttributeTypeAndValue:
		return 876
	case pkix.AttributeTypeAndValueSET:
		return 877
	case pkix.CertificateList:
		return 878
	case pkix.Extension:
		return 879
	case pkix.Name:
		return 880
	case pkix.RDNSequence:
		return 881
	case pkix.RelativeDistinguishedNameSET:
		return 882
	case pkix.RevokedCertificate:
		return 883
	case pkix.TBSCertificateList:
		return 884
	case x509.CertPool:
		return 885
	case x509.Certificate:
		return 886
	case x509.CertificateInvalidError:
		return 887
	case x509.CertificateRequest:
		return 888
	case x509.ConstraintViolationError:
		return 889
	case x509.ExtKeyUsage:
		return 890
	case x509.HostnameError:
		return 891
	case x509.InsecureAlgorithmError:
		return 892
	case x509.InvalidReason:
		return 893
	case x509.KeyUsage:
		return 894
	case x509.PEMCipher:
		return 895
	case x509.PublicKeyAlgorithm:
		return 896
	case x509.SignatureAlgorithm:
		return 897
	case x509.SystemRootsError:
		return 898
	case x509.UnhandledCriticalExtension:
		return 899
	case x509.UnknownAuthorityError:
		return 900
	case x509.VerifyOptions:
		return 901
	case crypto.Hash:
		return 902
	case driver.IsolationLevel:
		return 903
	case driver.NamedValue:
		return 904
	case driver.NotNull:
		return 905
	case driver.Null:
		return 906
	case driver.RowsAffected:
		return 907
	case driver.TxOptions:
		return 908
	case sql.ColumnType:
		return 909
	case sql.Conn:
		return 910
	case sql.DB:
		return 911
	case sql.DBStats:
		return 912
	case sql.IsolationLevel:
		return 913
	case sql.NamedArg:
		return 914
	case sql.NullBool:
		return 915
	case sql.NullFloat64:
		return 916
	case sql.NullInt32:
		return 917
	case sql.NullInt64:
		return 918
	case sql.NullString:
		return 919
	case sql.NullTime:
		return 920
	case sql.Out:
		return 921
	case sql.RawBytes:
		return 922
	case sql.Row:
		return 923
	case sql.Rows:
		return 924
	case sql.Stmt:
		return 925
	case sql.Tx:
		return 926
	case sql.TxOptions:
		return 927
	case dwarf.AddrType:
		return 928
	case dwarf.ArrayType:
		return 929
	case dwarf.Attr:
		return 930
	case dwarf.BasicType:
		return 931
	case dwarf.BoolType:
		return 932
	case dwarf.CharType:
		return 933
	case dwarf.Class:
		return 934
	case dwarf.CommonType:
		return 935
	case dwarf.ComplexType:
		return 936
	case dwarf.Data:
		return 937
	case dwarf.DecodeError:
		return 938
	case dwarf.DotDotDotType:
		return 939
	case dwarf.Entry:
		return 940
	case dwarf.EnumType:
		return 941
	case dwarf.EnumValue:
		return 942
	case dwarf.Field:
		return 943
	case dwarf.FloatType:
		return 944
	case dwarf.FuncType:
		return 945
	case dwarf.IntType:
		return 946
	case dwarf.LineEntry:
		return 947
	case dwarf.LineFile:
		return 948
	case dwarf.LineReader:
		return 949
	case dwarf.LineReaderPos:
		return 950
	case dwarf.Offset:
		return 951
	case dwarf.PtrType:
		return 952
	case dwarf.QualType:
		return 953
	case dwarf.Reader:
		return 954
	case dwarf.StructField:
		return 955
	case dwarf.StructType:
		return 956
	case dwarf.Tag:
		return 957
	case dwarf.TypedefType:
		return 958
	case dwarf.UcharType:
		return 959
	case dwarf.UintType:
		return 960
	case dwarf.UnspecifiedType:
		return 961
	case dwarf.UnsupportedType:
		return 962
	case dwarf.VoidType:
		return 963
	case elf.Chdr32:
		return 964
	case elf.Chdr64:
		return 965
	case elf.Class:
		return 966
	case elf.CompressionType:
		return 967
	case elf.Data:
		return 968
	case elf.Dyn32:
		return 969
	case elf.Dyn64:
		return 970
	case elf.DynFlag:
		return 971
	case elf.DynTag:
		return 972
	case elf.File:
		return 973
	case elf.FileHeader:
		return 974
	case elf.FormatError:
		return 975
	case elf.Header32:
		return 976
	case elf.Header64:
		return 977
	case elf.ImportedSymbol:
		return 978
	case elf.Machine:
		return 979
	case elf.NType:
		return 980
	case elf.OSABI:
		return 981
	case elf.Prog:
		return 982
	case elf.Prog32:
		return 983
	case elf.Prog64:
		return 984
	case elf.ProgFlag:
		return 985
	case elf.ProgHeader:
		return 986
	case elf.ProgType:
		return 987
	case elf.R_386:
		return 988
	case elf.R_390:
		return 989
	case elf.R_AARCH64:
		return 990
	case elf.R_ALPHA:
		return 991
	case elf.R_ARM:
		return 992
	case elf.R_MIPS:
		return 993
	case elf.R_PPC:
		return 994
	case elf.R_PPC64:
		return 995
	case elf.R_RISCV:
		return 996
	case elf.R_SPARC:
		return 997
	case elf.R_X86_64:
		return 998
	case elf.Rel32:
		return 999
	case elf.Rel64:
		return 1000
	case elf.Rela32:
		return 1001
	case elf.Rela64:
		return 1002
	case elf.Section:
		return 1003
	case elf.Section32:
		return 1004
	case elf.Section64:
		return 1005
	case elf.SectionFlag:
		return 1006
	case elf.SectionHeader:
		return 1007
	case elf.SectionIndex:
		return 1008
	case elf.SectionType:
		return 1009
	case elf.Sym32:
		return 1010
	case elf.Sym64:
		return 1011
	case elf.SymBind:
		return 1012
	case elf.SymType:
		return 1013
	case elf.SymVis:
		return 1014
	case elf.Symbol:
		return 1015
	case elf.Type:
		return 1016
	case elf.Version:
		return 1017
	case gosym.DecodingError:
		return 1018
	case gosym.Func:
		return 1019
	case gosym.LineTable:
		return 1020
	case gosym.Obj:
		return 1021
	case gosym.Sym:
		return 1022
	case gosym.Table:
		return 1023
	case gosym.UnknownFileError:
		return 1024
	case gosym.UnknownLineError:
		return 1025
	case macho.Cpu:
		return 1026
	case macho.Dylib:
		return 1027
	case macho.DylibCmd:
		return 1028
	case macho.Dysymtab:
		return 1029
	case macho.DysymtabCmd:
		return 1030
	case macho.FatArch:
		return 1031
	case macho.FatArchHeader:
		return 1032
	case macho.FatFile:
		return 1033
	case macho.File:
		return 1034
	case macho.FileHeader:
		return 1035
	case macho.FormatError:
		return 1036
	case macho.LoadBytes:
		return 1037
	case macho.LoadCmd:
		return 1038
	case macho.Nlist32:
		return 1039
	case macho.Nlist64:
		return 1040
	case macho.Regs386:
		return 1041
	case macho.RegsAMD64:
		return 1042
	case macho.Reloc:
		return 1043
	case macho.RelocTypeARM:
		return 1044
	case macho.RelocTypeARM64:
		return 1045
	case macho.RelocTypeGeneric:
		return 1046
	case macho.RelocTypeX86_64:
		return 1047
	case macho.Rpath:
		return 1048
	case macho.RpathCmd:
		return 1049
	case macho.Section:
		return 1050
	case macho.Section32:
		return 1051
	case macho.Section64:
		return 1052
	case macho.SectionHeader:
		return 1053
	case macho.Segment:
		return 1054
	case macho.Segment32:
		return 1055
	case macho.Segment64:
		return 1056
	case macho.SegmentHeader:
		return 1057
	case macho.Symbol:
		return 1058
	case macho.Symtab:
		return 1059
	case macho.SymtabCmd:
		return 1060
	case macho.Thread:
		return 1061
	case macho.Type:
		return 1062
	case pe.COFFSymbol:
		return 1063
	case pe.DataDirectory:
		return 1064
	case pe.File:
		return 1065
	case pe.FileHeader:
		return 1066
	case pe.FormatError:
		return 1067
	case pe.ImportDirectory:
		return 1068
	case pe.OptionalHeader32:
		return 1069
	case pe.OptionalHeader64:
		return 1070
	case pe.Reloc:
		return 1071
	case pe.Section:
		return 1072
	case pe.SectionHeader:
		return 1073
	case pe.SectionHeader32:
		return 1074
	case pe.StringTable:
		return 1075
	case pe.Symbol:
		return 1076
	case plan9obj.File:
		return 1077
	case plan9obj.FileHeader:
		return 1078
	case plan9obj.Section:
		return 1079
	case plan9obj.SectionHeader:
		return 1080
	case plan9obj.Sym:
		return 1081
	case ascii85.CorruptInputError:
		return 1082
	case asn1.BitString:
		return 1083
	case asn1.Enumerated:
		return 1084
	case asn1.Flag:
		return 1085
	case asn1.ObjectIdentifier:
		return 1086
	case asn1.RawContent:
		return 1087
	case asn1.RawValue:
		return 1088
	case asn1.StructuralError:
		return 1089
	case asn1.SyntaxError:
		return 1090
	case base32.CorruptInputError:
		return 1091
	case base32.Encoding:
		return 1092
	case base64.CorruptInputError:
		return 1093
	case base64.Encoding:
		return 1094
	case csv.ParseError:
		return 1095
	case csv.Reader:
		return 1096
	case csv.Writer:
		return 1097
	case gob.CommonType:
		return 1098
	case gob.Decoder:
		return 1099
	case gob.Encoder:
		return 1100
	case hex.InvalidByteError:
		return 1101
	case json.Decoder:
		return 1102
	case json.Delim:
		return 1103
	case json.Encoder:
		return 1104
	case json.InvalidUTF8Error:
		return 1105
	case json.InvalidUnmarshalError:
		return 1106
	case json.MarshalerError:
		return 1107
	case json.Number:
		return 1108
	case json.RawMessage:
		return 1109
	case json.SyntaxError:
		return 1110
	case json.UnmarshalFieldError:
		return 1111
	case json.UnmarshalTypeError:
		return 1112
	case json.UnsupportedTypeError:
		return 1113
	case json.UnsupportedValueError:
		return 1114
	case pem.Block:
		return 1115
	case xml.Attr:
		return 1116
	case xml.CharData:
		return 1117
	case xml.Comment:
		return 1118
	case xml.Decoder:
		return 1119
	case xml.Directive:
		return 1120
	case xml.Encoder:
		return 1121
	case xml.EndElement:
		return 1122
	case xml.Name:
		return 1123
	case xml.ProcInst:
		return 1124
	case xml.StartElement:
		return 1125
	case xml.SyntaxError:
		return 1126
	case xml.TagPathError:
		return 1127
	case xml.UnmarshalError:
		return 1128
	case xml.UnsupportedTypeError:
		return 1129
	case expvar.Float:
		return 1130
	case expvar.Func:
		return 1131
	case expvar.Int:
		return 1132
	case expvar.KeyValue:
		return 1133
	case expvar.Map:
		return 1134
	case expvar.String:
		return 1135
	case flag.ErrorHandling:
		return 1136
	case flag.Flag:
		return 1137
	case flag.FlagSet:
		return 1138
	case ast.ArrayType:
		return 1139
	case ast.AssignStmt:
		return 1140
	case ast.BadDecl:
		return 1141
	case ast.BadExpr:
		return 1142
	case ast.BadStmt:
		return 1143
	case ast.BasicLit:
		return 1144
	case ast.BinaryExpr:
		return 1145
	case ast.BlockStmt:
		return 1146
	case ast.BranchStmt:
		return 1147
	case ast.CallExpr:
		return 1148
	case ast.CaseClause:
		return 1149
	case ast.ChanDir:
		return 1150
	case ast.ChanType:
		return 1151
	case ast.CommClause:
		return 1152
	case ast.Comment:
		return 1153
	case ast.CommentGroup:
		return 1154
	case ast.CommentMap:
		return 1155
	case ast.CompositeLit:
		return 1156
	case ast.DeclStmt:
		return 1157
	case ast.DeferStmt:
		return 1158
	case ast.Ellipsis:
		return 1159
	case ast.EmptyStmt:
		return 1160
	case ast.ExprStmt:
		return 1161
	case ast.Field:
		return 1162
	case ast.FieldFilter:
		return 1163
	case ast.FieldList:
		return 1164
	case ast.File:
		return 1165
	case ast.Filter:
		return 1166
	case ast.ForStmt:
		return 1167
	case ast.FuncDecl:
		return 1168
	case ast.FuncLit:
		return 1169
	case ast.FuncType:
		return 1170
	case ast.GenDecl:
		return 1171
	case ast.GoStmt:
		return 1172
	case ast.Ident:
		return 1173
	case ast.IfStmt:
		return 1174
	case ast.ImportSpec:
		return 1175
	case ast.Importer:
		return 1176
	case ast.IncDecStmt:
		return 1177
	case ast.IndexExpr:
		return 1178
	case ast.InterfaceType:
		return 1179
	case ast.KeyValueExpr:
		return 1180
	case ast.LabeledStmt:
		return 1181
	case ast.MapType:
		return 1182
	case ast.MergeMode:
		return 1183
	case ast.ObjKind:
		return 1184
	case ast.Object:
		return 1185
	case ast.Package:
		return 1186
	case ast.ParenExpr:
		return 1187
	case ast.RangeStmt:
		return 1188
	case ast.ReturnStmt:
		return 1189
	case ast.Scope:
		return 1190
	case ast.SelectStmt:
		return 1191
	case ast.SelectorExpr:
		return 1192
	case ast.SendStmt:
		return 1193
	case ast.SliceExpr:
		return 1194
	case ast.StarExpr:
		return 1195
	case ast.StructType:
		return 1196
	case ast.SwitchStmt:
		return 1197
	case ast.TypeAssertExpr:
		return 1198
	case ast.TypeSpec:
		return 1199
	case ast.TypeSwitchStmt:
		return 1200
	case ast.UnaryExpr:
		return 1201
	case ast.ValueSpec:
		return 1202
	case build.Context:
		return 1203
	case build.ImportMode:
		return 1204
	case build.MultiplePackageError:
		return 1205
	case build.NoGoError:
		return 1206
	case build.Package:
		return 1207
	case constant.Kind:
		return 1208
	case doc.Example:
		return 1209
	case doc.Filter:
		return 1210
	case doc.Func:
		return 1211
	case doc.Mode:
		return 1212
	case doc.Note:
		return 1213
	case doc.Package:
		return 1214
	case doc.Type:
		return 1215
	case doc.Value:
		return 1216
	case importer.Lookup:
		return 1217
	case parser.Mode:
		return 1218
	case printer.CommentedNode:
		return 1219
	case printer.Config:
		return 1220
	case printer.Mode:
		return 1221
	case scanner.Error:
		return 1222
	case scanner.ErrorHandler:
		return 1223
	case scanner.ErrorList:
		return 1224
	case scanner.Mode:
		return 1225
	case scanner.Scanner:
		return 1226
	case token.File:
		return 1227
	case token.FileSet:
		return 1228
	case token.Pos:
		return 1229
	case token.Position:
		return 1230
	case token.Token:
		return 1231
	case types.Array:
		return 1232
	case types.Basic:
		return 1233
	case types.BasicInfo:
		return 1234
	case types.BasicKind:
		return 1235
	case types.Builtin:
		return 1236
	case types.Chan:
		return 1237
	case types.ChanDir:
		return 1238
	case types.Checker:
		return 1239
	case types.Config:
		return 1240
	case types.Const:
		return 1241
	case types.Error:
		return 1242
	case types.Func:
		return 1243
	case types.ImportMode:
		return 1244
	case types.Info:
		return 1245
	case types.Initializer:
		return 1246
	case types.Interface:
		return 1247
	case types.Label:
		return 1248
	case types.Map:
		return 1249
	case types.MethodSet:
		return 1250
	case types.Named:
		return 1251
	case types.Nil:
		return 1252
	case types.Package:
		return 1253
	case types.PkgName:
		return 1254
	case types.Pointer:
		return 1255
	case types.Qualifier:
		return 1256
	case types.Scope:
		return 1257
	case types.Selection:
		return 1258
	case types.SelectionKind:
		return 1259
	case types.Signature:
		return 1260
	case types.Slice:
		return 1261
	case types.StdSizes:
		return 1262
	case types.Struct:
		return 1263
	case types.Tuple:
		return 1264
	case types.TypeAndValue:
		return 1265
	case types.TypeName:
		return 1266
	case types.Var:
		return 1267
	case crc32.Table:
		return 1268
	case crc64.Table:
		return 1269
	case template.CSS:
		return 1270
	case template.Error:
		return 1271
	case template.ErrorCode:
		return 1272
	case template.FuncMap:
		return 1273
	case template.HTML:
		return 1274
	case template.HTMLAttr:
		return 1275
	case template.JS:
		return 1276
	case template.JSStr:
		return 1277
	case template.Srcset:
		return 1278
	case template.Template:
		return 1279
	case template.URL:
		return 1280
	case color.Alpha:
		return 1281
	case color.Alpha16:
		return 1282
	case color.CMYK:
		return 1283
	case color.Gray:
		return 1284
	case color.Gray16:
		return 1285
	case color.NRGBA:
		return 1286
	case color.NRGBA64:
		return 1287
	case color.NYCbCrA:
		return 1288
	case color.Palette:
		return 1289
	case color.RGBA:
		return 1290
	case color.RGBA64:
		return 1291
	case color.YCbCr:
		return 1292
	case draw.Op:
		return 1293
	case gif.GIF:
		return 1294
	case gif.Options:
		return 1295
	case jpeg.FormatError:
		return 1296
	case jpeg.Options:
		return 1297
	case jpeg.UnsupportedError:
		return 1298
	case png.CompressionLevel:
		return 1299
	case png.Encoder:
		return 1300
	case png.EncoderBuffer:
		return 1301
	case png.FormatError:
		return 1302
	case png.UnsupportedError:
		return 1303
	case image.Alpha:
		return 1304
	case image.Alpha16:
		return 1305
	case image.CMYK:
		return 1306
	case image.Config:
		return 1307
	case image.Gray:
		return 1308
	case image.Gray16:
		return 1309
	case image.NRGBA:
		return 1310
	case image.NRGBA64:
		return 1311
	case image.NYCbCrA:
		return 1312
	case image.Paletted:
		return 1313
	case image.Point:
		return 1314
	case image.RGBA:
		return 1315
	case image.RGBA64:
		return 1316
	case image.Rectangle:
		return 1317
	case image.Uniform:
		return 1318
	case image.YCbCr:
		return 1319
	case image.YCbCrSubsampleRatio:
		return 1320
	case suffixarray.Index:
		return 1321
	case io.LimitedReader:
		return 1322
	case io.PipeReader:
		return 1323
	case io.PipeWriter:
		return 1324
	case io.SectionReader:
		return 1325
	case syslog.Priority:
		return 1326
	case syslog.Writer:
		return 1327
	case log.Logger:
		return 1328
	case big.Accuracy:
		return 1329
	case big.ErrNaN:
		return 1330
	case big.Float:
		return 1331
	case big.Int:
		return 1332
	case big.Rat:
		return 1333
	case big.RoundingMode:
		return 1334
	case big.Word:
		return 1335
	case rand.Rand:
		return 1336
	case rand.Zipf:
		return 1337
	case multipart.FileHeader:
		return 1338
	case multipart.Form:
		return 1339
	case multipart.Part:
		return 1340
	case multipart.Reader:
		return 1341
	case multipart.Writer:
		return 1342
	case quotedprintable.Reader:
		return 1343
	case quotedprintable.Writer:
		return 1344
	case mime.WordDecoder:
		return 1345
	case mime.WordEncoder:
		return 1346
	case cgi.Handler:
		return 1347
	case cookiejar.Jar:
		return 1348
	case cookiejar.Options:
		return 1349
	case httptest.ResponseRecorder:
		return 1350
	case httptest.Server:
		return 1351
	case httptrace.ClientTrace:
		return 1352
	case httptrace.DNSDoneInfo:
		return 1353
	case httptrace.DNSStartInfo:
		return 1354
	case httptrace.GotConnInfo:
		return 1355
	case httptrace.WroteRequestInfo:
		return 1356
	case httputil.ClientConn:
		return 1357
	case httputil.ReverseProxy:
		return 1358
	case httputil.ServerConn:
		return 1359
	case http.Client:
		return 1360
	case http.ConnState:
		return 1361
	case http.Cookie:
		return 1362
	case http.Dir:
		return 1363
	case http.HandlerFunc:
		return 1364
	case http.Header:
		return 1365
	case http.ProtocolError:
		return 1366
	case http.PushOptions:
		return 1367
	case http.Request:
		return 1368
	case http.Response:
		return 1369
	case http.SameSite:
		return 1370
	case http.ServeMux:
		return 1371
	case http.Server:
		return 1372
	case http.Transport:
		return 1373
	case mail.Address:
		return 1374
	case mail.AddressParser:
		return 1375
	case mail.Header:
		return 1376
	case mail.Message:
		return 1377
	case rpc.Call:
		return 1378
	case rpc.Client:
		return 1379
	case rpc.Request:
		return 1380
	case rpc.Response:
		return 1381
	case rpc.Server:
		return 1382
	case rpc.ServerError:
		return 1383
	case smtp.Client:
		return 1384
	case smtp.ServerInfo:
		return 1385
	case textproto.Conn:
		return 1386
	case textproto.Error:
		return 1387
	case textproto.MIMEHeader:
		return 1388
	case textproto.Pipeline:
		return 1389
	case textproto.ProtocolError:
		return 1390
	case textproto.Reader:
		return 1391
	case textproto.Writer:
		return 1392
	case url.Error:
		return 1393
	case url.EscapeError:
		return 1394
	case url.InvalidHostError:
		return 1395
	case url.URL:
		return 1396
	case url.Userinfo:
		return 1397
	case url.Values:
		return 1398
	case net.AddrError:
		return 1399
	case net.Buffers:
		return 1400
	case net.DNSConfigError:
		return 1401
	case net.DNSError:
		return 1402
	case net.Dialer:
		return 1403
	case net.Flags:
		return 1404
	case net.HardwareAddr:
		return 1405
	case net.IP:
		return 1406
	case net.IPAddr:
		return 1407
	case net.IPConn:
		return 1408
	case net.IPMask:
		return 1409
	case net.IPNet:
		return 1410
	case net.Interface:
		return 1411
	case net.InvalidAddrError:
		return 1412
	case net.ListenConfig:
		return 1413
	case net.MX:
		return 1414
	case net.NS:
		return 1415
	case net.OpError:
		return 1416
	case net.ParseError:
		return 1417
	case net.Resolver:
		return 1418
	case net.SRV:
		return 1419
	case net.TCPAddr:
		return 1420
	case net.TCPConn:
		return 1421
	case net.TCPListener:
		return 1422
	case net.UDPAddr:
		return 1423
	case net.UDPConn:
		return 1424
	case net.UnixAddr:
		return 1425
	case net.UnixConn:
		return 1426
	case net.UnixListener:
		return 1427
	case net.UnknownNetworkError:
		return 1428
	case exec.Cmd:
		return 1429
	case exec.Error:
		return 1430
	case exec.ExitError:
		return 1431
	case user.Group:
		return 1432
	case user.UnknownGroupError:
		return 1433
	case user.UnknownGroupIdError:
		return 1434
	case user.UnknownUserError:
		return 1435
	case user.UnknownUserIdError:
		return 1436
	case user.User:
		return 1437
	case os.File:
		return 1438
	case os.FileMode:
		return 1439
	case os.LinkError:
		return 1440
	case os.PathError:
		return 1441
	case os.ProcAttr:
		return 1442
	case os.Process:
		return 1443
	case os.ProcessState:
		return 1444
	case os.SyscallError:
		return 1445
	case filepath.WalkFunc:
		return 1446
	case plugin.Plugin:
		return 1447
	case reflect.ChanDir:
		return 1448
	case reflect.Kind:
		return 1449
	case reflect.MapIter:
		return 1450
	case reflect.Method:
		return 1451
	case reflect.SelectCase:
		return 1452
	case reflect.SelectDir:
		return 1453
	case reflect.SliceHeader:
		return 1454
	case reflect.StringHeader:
		return 1455
	case reflect.StructField:
		return 1456
	case reflect.StructTag:
		return 1457
	case reflect.Value:
		return 1458
	case reflect.ValueError:
		return 1459
	case syntax.EmptyOp:
		return 1460
	case syntax.Error:
		return 1461
	case syntax.ErrorCode:
		return 1462
	case syntax.Flags:
		return 1463
	case syntax.Inst:
		return 1464
	case syntax.InstOp:
		return 1465
	case syntax.Op:
		return 1466
	case syntax.Prog:
		return 1467
	case syntax.Regexp:
		return 1468
	case regexp.Regexp:
		return 1469
	case debug.BuildInfo:
		return 1470
	case debug.GCStats:
		return 1471
	case debug.Module:
		return 1472
	case pprof.LabelSet:
		return 1473
	case pprof.Profile:
		return 1474
	case trace.Region:
		return 1475
	case trace.Task:
		return 1476
	case runtime.BlockProfileRecord:
		return 1477
	case runtime.Frame:
		return 1478
	case runtime.Frames:
		return 1479
	case runtime.Func:
		return 1480
	case runtime.MemProfileRecord:
		return 1481
	case runtime.MemStats:
		return 1482
	case runtime.StackRecord:
		return 1483
	case runtime.TypeAssertionError:
		return 1484
	case sort.Float64Slice:
		return 1485
	case sort.IntSlice:
		return 1486
	case sort.StringSlice:
		return 1487
	case strconv.NumError:
		return 1488
	case strings.Builder:
		return 1489
	case strings.Reader:
		return 1490
	case strings.Replacer:
		return 1491
	case atomic.Value:
		return 1492
	case sync.Cond:
		return 1493
	case sync.Map:
		return 1494
	case sync.Mutex:
		return 1495
	case sync.Once:
		return 1496
	case sync.Pool:
		return 1497
	case sync.RWMutex:
		return 1498
	case sync.WaitGroup:
		return 1499
	case syscall.BpfHdr:
		return 1500
	case syscall.BpfInsn:
		return 1501
	case syscall.BpfProgram:
		return 1502
	case syscall.BpfStat:
		return 1503
	case syscall.BpfVersion:
		return 1504
	case syscall.Cmsghdr:
		return 1505
	case syscall.Credential:
		return 1506
	case syscall.Dirent:
		return 1507
	case syscall.Errno:
		return 1508
	case syscall.Fbootstraptransfer_t:
		return 1509
	case syscall.FdSet:
		return 1510
	case syscall.Flock_t:
		return 1511
	case syscall.Fsid:
		return 1512
	case syscall.Fstore_t:
		return 1513
	case syscall.ICMPv6Filter:
		return 1514
	case syscall.IPMreq:
		return 1515
	case syscall.IPv6MTUInfo:
		return 1516
	case syscall.IPv6Mreq:
		return 1517
	case syscall.IfData:
		return 1518
	case syscall.IfMsghdr:
		return 1519
	case syscall.IfaMsghdr:
		return 1520
	case syscall.IfmaMsghdr:
		return 1521
	case syscall.IfmaMsghdr2:
		return 1522
	case syscall.Inet4Pktinfo:
		return 1523
	case syscall.Inet6Pktinfo:
		return 1524
	case syscall.InterfaceAddrMessage:
		return 1525
	case syscall.InterfaceMessage:
		return 1526
	case syscall.InterfaceMulticastAddrMessage:
		return 1527
	case syscall.Iovec:
		return 1528
	case syscall.Kevent_t:
		return 1529
	case syscall.Linger:
		return 1530
	case syscall.Log2phys_t:
		return 1531
	case syscall.Msghdr:
		return 1532
	case syscall.ProcAttr:
		return 1533
	case syscall.Radvisory_t:
		return 1534
	case syscall.RawSockaddr:
		return 1535
	case syscall.RawSockaddrAny:
		return 1536
	case syscall.RawSockaddrDatalink:
		return 1537
	case syscall.RawSockaddrInet4:
		return 1538
	case syscall.RawSockaddrInet6:
		return 1539
	case syscall.RawSockaddrUnix:
		return 1540
	case syscall.Rlimit:
		return 1541
	case syscall.RouteMessage:
		return 1542
	case syscall.RtMetrics:
		return 1543
	case syscall.RtMsghdr:
		return 1544
	case syscall.Rusage:
		return 1545
	case syscall.Signal:
		return 1546
	case syscall.SockaddrDatalink:
		return 1547
	case syscall.SockaddrInet4:
		return 1548
	case syscall.SockaddrInet6:
		return 1549
	case syscall.SockaddrUnix:
		return 1550
	case syscall.SocketControlMessage:
		return 1551
	case syscall.Stat_t:
		return 1552
	case syscall.Statfs_t:
		return 1553
	case syscall.SysProcAttr:
		return 1554
	case syscall.Termios:
		return 1555
	case syscall.Timespec:
		return 1556
	case syscall.Timeval:
		return 1557
	case syscall.Timeval32:
		return 1558
	case syscall.WaitStatus:
		return 1559
	case quick.CheckEqualError:
		return 1560
	case quick.CheckError:
		return 1561
	case quick.Config:
		return 1562
	case quick.SetupError:
		return 1563
	case testing.B:
		return 1564
	case testing.BenchmarkResult:
		return 1565
	case testing.Cover:
		return 1566
	case testing.CoverBlock:
		return 1567
	case testing.InternalBenchmark:
		return 1568
	case testing.InternalExample:
		return 1569
	case testing.InternalTest:
		return 1570
	case testing.M:
		return 1571
	case testing.PB:
		return 1572
	case testing.T:
		return 1573
	case text_scanner.Position:
		return 1574
	case text_scanner.Scanner:
		return 1575
	case tabwriter.Writer:
		return 1576
	case parse.ActionNode:
		return 1577
	case parse.BoolNode:
		return 1578
	case parse.BranchNode:
		return 1579
	case parse.ChainNode:
		return 1580
	case parse.CommandNode:
		return 1581
	case parse.DotNode:
		return 1582
	case parse.FieldNode:
		return 1583
	case parse.IdentifierNode:
		return 1584
	case parse.IfNode:
		return 1585
	case parse.ListNode:
		return 1586
	case parse.NilNode:
		return 1587
	case parse.NodeType:
		return 1588
	case parse.NumberNode:
		return 1589
	case parse.PipeNode:
		return 1590
	case parse.Pos:
		return 1591
	case parse.RangeNode:
		return 1592
	case parse.StringNode:
		return 1593
	case parse.TemplateNode:
		return 1594
	case parse.TextNode:
		return 1595
	case parse.Tree:
		return 1596
	case parse.VariableNode:
		return 1597
	case parse.WithNode:
		return 1598
	case text_template.ExecError:
		return 1599
	case text_template.FuncMap:
		return 1600
	case text_template.Template:
		return 1601
	case time.Duration:
		return 1602
	case time.Location:
		return 1603
	case time.Month:
		return 1604
	case time.ParseError:
		return 1605
	case time.Ticker:
		return 1606
	case time.Time:
		return 1607
	case time.Timer:
		return 1608
	case time.Weekday:
		return 1609
	case unicode.CaseRange:
		return 1610
	case unicode.Range16:
		return 1611
	case unicode.Range32:
		return 1612
	case unicode.RangeTable:
		return 1613
	case unicode.SpecialCase:
		return 1614
	case unsafe.Pointer:
		return 1615
	case reflect.Type:  // Specificity=31
		return 1616
	case types.Object:  // Specificity=16
		return 1617
	case testing.TB:  // Specificity=16
		return 1618
	case net.Conn:  // Specificity=8
		return 1619
	case binary.ByteOrder:  // Specificity=7
		return 1620
	case net.PacketConn:  // Specificity=7
		return 1621
	case elliptic.Curve:  // Specificity=6
		return 1622
	case fmt.ScanState:  // Specificity=6
		return 1623
	case hash.Hash32:  // Specificity=6
		return 1624
	case hash.Hash64:  // Specificity=6
		return 1625
	case os.FileInfo:  // Specificity=6
		return 1626
	case heap.Interface:  // Specificity=5
		return 1627
	case driver.RowsNextResultSet:  // Specificity=5
		return 1628
	case hash.Hash:  // Specificity=5
		return 1629
	case http.File:  // Specificity=5
		return 1630
	case parse.Node:  // Specificity=5
		return 1631
	case context.Context:  // Specificity=4
		return 1632
	case cipher.AEAD:  // Specificity=4
		return 1633
	case driver.RowsColumnTypeDatabaseTypeName:  // Specificity=4
		return 1634
	case driver.RowsColumnTypeLength:  // Specificity=4
		return 1635
	case driver.RowsColumnTypeNullable:  // Specificity=4
		return 1636
	case driver.RowsColumnTypePrecisionScale:  // Specificity=4
		return 1637
	case driver.RowsColumnTypeScanType:  // Specificity=4
		return 1638
	case driver.Stmt:  // Specificity=4
		return 1639
	case fmt.State:  // Specificity=4
		return 1640
	case constant.Value:  // Specificity=4
		return 1641
	case draw.Image:  // Specificity=4
		return 1642
	case image.PalettedImage:  // Specificity=4
		return 1643
	case multipart.File:  // Specificity=4
		return 1644
	case rpc.ClientCodec:  // Specificity=4
		return 1645
	case rpc.ServerCodec:  // Specificity=4
		return 1646
	case cipher.Block:  // Specificity=3
		return 1647
	case driver.Conn:  // Specificity=3
		return 1648
	case driver.Rows:  // Specificity=3
		return 1649
	case dwarf.Type:  // Specificity=3
		return 1650
	case flag.Getter:  // Specificity=3
		return 1651
	case ast.Decl:  // Specificity=3
		return 1652
	case ast.Expr:  // Specificity=3
		return 1653
	case ast.Spec:  // Specificity=3
		return 1654
	case ast.Stmt:  // Specificity=3
		return 1655
	case types.Sizes:  // Specificity=3
		return 1656
	case image.Image:  // Specificity=3
		return 1657
	case io.ReadWriteCloser:  // Specificity=3
		return 1658
	case io.ReadWriteSeeker:  // Specificity=3
		return 1659
	case rand.Source64:  // Specificity=3
		return 1660
	case http.ResponseWriter:  // Specificity=3
		return 1661
	case net.Error:  // Specificity=3
		return 1662
	case net.Listener:  // Specificity=3
		return 1663
	case sort.Interface:  // Specificity=3
		return 1664
	case syscall.RawConn:  // Specificity=3
		return 1665
	case flate.Reader:  // Specificity=2
		return 1666
	case cipher.BlockMode:  // Specificity=2
		return 1667
	case tls.ClientSessionCache:  // Specificity=2
		return 1668
	case crypto.Decrypter:  // Specificity=2
		return 1669
	case crypto.Signer:  // Specificity=2
		return 1670
	case driver.Connector:  // Specificity=2
		return 1671
	case driver.Result:  // Specificity=2
		return 1672
	case driver.Tx:  // Specificity=2
		return 1673
	case sql.Result:  // Specificity=2
		return 1674
	case flag.Value:  // Specificity=2
		return 1675
	case ast.Node:  // Specificity=2
		return 1676
	case types.ImporterFrom:  // Specificity=2
		return 1677
	case types.Type:  // Specificity=2
		return 1678
	case jpeg.Reader:  // Specificity=2
		return 1679
	case png.EncoderBufferPool:  // Specificity=2
		return 1680
	case io.ByteScanner:  // Specificity=2
		return 1681
	case io.ReadCloser:  // Specificity=2
		return 1682
	case io.ReadSeeker:  // Specificity=2
		return 1683
	case io.ReadWriter:  // Specificity=2
		return 1684
	case io.RuneScanner:  // Specificity=2
		return 1685
	case io.WriteCloser:  // Specificity=2
		return 1686
	case io.WriteSeeker:  // Specificity=2
		return 1687
	case rand.Source:  // Specificity=2
		return 1688
	case cookiejar.PublicSuffixList:  // Specificity=2
		return 1689
	case httputil.BufferPool:  // Specificity=2
		return 1690
	case http.CookieJar:  // Specificity=2
		return 1691
	case smtp.Auth:  // Specificity=2
		return 1692
	case net.Addr:  // Specificity=2
		return 1693
	case os.Signal:  // Specificity=2
		return 1694
	case runtime.Error:  // Specificity=2
		return 1695
	case sync.Locker:  // Specificity=2
		return 1696
	case flate.Resetter:  // Specificity=1
		return 1697
	case zlib.Resetter:  // Specificity=1
		return 1698
	case cipher.Stream:  // Specificity=1
		return 1699
	case crypto.SignerOpts:  // Specificity=1
		return 1700
	case driver.ColumnConverter:  // Specificity=1
		return 1701
	case driver.ConnBeginTx:  // Specificity=1
		return 1702
	case driver.ConnPrepareContext:  // Specificity=1
		return 1703
	case driver.Driver:  // Specificity=1
		return 1704
	case driver.DriverContext:  // Specificity=1
		return 1705
	case driver.Execer:  // Specificity=1
		return 1706
	case driver.ExecerContext:  // Specificity=1
		return 1707
	case driver.NamedValueChecker:  // Specificity=1
		return 1708
	case driver.Pinger:  // Specificity=1
		return 1709
	case driver.Queryer:  // Specificity=1
		return 1710
	case driver.QueryerContext:  // Specificity=1
		return 1711
	case driver.SessionResetter:  // Specificity=1
		return 1712
	case driver.StmtExecContext:  // Specificity=1
		return 1713
	case driver.StmtQueryContext:  // Specificity=1
		return 1714
	case driver.ValueConverter:  // Specificity=1
		return 1715
	case driver.Valuer:  // Specificity=1
		return 1716
	case sql.Scanner:  // Specificity=1
		return 1717
	case macho.Load:  // Specificity=1
		return 1718
	case gob.GobDecoder:  // Specificity=1
		return 1719
	case gob.GobEncoder:  // Specificity=1
		return 1720
	case json.Marshaler:  // Specificity=1
		return 1721
	case json.Unmarshaler:  // Specificity=1
		return 1722
	case xml.Marshaler:  // Specificity=1
		return 1723
	case xml.MarshalerAttr:  // Specificity=1
		return 1724
	case xml.TokenReader:  // Specificity=1
		return 1725
	case xml.Unmarshaler:  // Specificity=1
		return 1726
	case xml.UnmarshalerAttr:  // Specificity=1
		return 1727
	case encoding.BinaryMarshaler:  // Specificity=1
		return 1728
	case encoding.BinaryUnmarshaler:  // Specificity=1
		return 1729
	case encoding.TextMarshaler:  // Specificity=1
		return 1730
	case encoding.TextUnmarshaler:  // Specificity=1
		return 1731
	case expvar.Var:  // Specificity=1
		return 1732
	case fmt.Formatter:  // Specificity=1
		return 1733
	case fmt.GoStringer:  // Specificity=1
		return 1734
	case fmt.Scanner:  // Specificity=1
		return 1735
	case fmt.Stringer:  // Specificity=1
		return 1736
	case ast.Visitor:  // Specificity=1
		return 1737
	case types.Importer:  // Specificity=1
		return 1738
	case color.Color:  // Specificity=1
		return 1739
	case color.Model:  // Specificity=1
		return 1740
	case draw.Drawer:  // Specificity=1
		return 1741
	case draw.Quantizer:  // Specificity=1
		return 1742
	case io.ByteReader:  // Specificity=1
		return 1743
	case io.ByteWriter:  // Specificity=1
		return 1744
	case io.Closer:  // Specificity=1
		return 1745
	case io.Reader:  // Specificity=1
		return 1746
	case io.ReaderAt:  // Specificity=1
		return 1747
	case io.ReaderFrom:  // Specificity=1
		return 1748
	case io.RuneReader:  // Specificity=1
		return 1749
	case io.Seeker:  // Specificity=1
		return 1750
	case io.StringWriter:  // Specificity=1
		return 1751
	case io.Writer:  // Specificity=1
		return 1752
	case io.WriterAt:  // Specificity=1
		return 1753
	case io.WriterTo:  // Specificity=1
		return 1754
	case http.CloseNotifier:  // Specificity=1
		return 1755
	case http.FileSystem:  // Specificity=1
		return 1756
	case http.Flusher:  // Specificity=1
		return 1757
	case http.Handler:  // Specificity=1
		return 1758
	case http.Hijacker:  // Specificity=1
		return 1759
	case http.Pusher:  // Specificity=1
		return 1760
	case http.RoundTripper:  // Specificity=1
		return 1761
	case syscall.Conn:  // Specificity=1
		return 1762
	case syscall.RoutingMessage:  // Specificity=1
		return 1763
	case syscall.Sockaddr:  // Specificity=1
		return 1764
	case quick.Generator:  // Specificity=1
		return 1765
	}
	return -1
}
