// Auto-generated by gostd at 2019-09-17T13:14:28.216621211-04:00 by version 0.1, do not edit!!

package jsonrpc

import (
	. "github.com/candid82/joker/core"
	_jsonrpc "net/rpc/jsonrpc"
)

func __dial(__network string, __address string) Object {
	_res1, _res2 := _jsonrpc.Dial(__network, __address)
	_res := EmptyVector()
	_res = _res.Conjoin(MakeGoObject(_res1))
	_res = _res.Conjoin(func () Object { if (_res2) == nil { return NIL } else { return MakeError(_res2) } }())
	return _res
}

// func __newClient(__conn ABEND987(genutils.go: imports not yet supported: io.ReadWriteCloser)) Object {
// 	_res := _jsonrpc.NewClient(__conn)
// 	return MakeGoObject(_res)
// }

// func __newClientCodec(__conn ABEND987(genutils.go: imports not yet supported: io.ReadWriteCloser)) Object {
// 	_res := _jsonrpc.NewClientCodec(__conn)
// 	return MakeGoObject(_res)
// }

// func __newServerCodec(__conn ABEND987(genutils.go: imports not yet supported: io.ReadWriteCloser)) Object {
// 	_res := _jsonrpc.NewServerCodec(__conn)
// 	return MakeGoObject(_res)
// }

// func __serveConn(__conn ABEND987(genutils.go: imports not yet supported: io.ReadWriteCloser)) Object {
// 	_jsonrpc.ServeConn(__conn)
// 	...ABEND675: TODO...
// }

func initNative() {
}
